highlighter: pygments
permalink:   pretty

# Setup
title:       Flog
tagline:     Slow but Steady
url:         https://bigbes.github.io/
baseurl:     /
paginate:    10

sass:
    sass_dir: _sass
    style:    :compressed

author:
  name:           'Eugine Blikh'
  url:            bigbes.github.io
  email:          bigbes@gmail.com

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
