baseUrl = "bigb.es"
languageCode = "en-us"
title = "strange invitation"
theme = 'archie'
copyright = "bigbes"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 5

[params]
    mode = "auto" # color-mode → light,dark,toggle or auto
    useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
    subtitle = "some thoughts on different aspects of programming"
    mathjax = true # enable MathJax support
    katex = true # enable KaTeX support
    customCSS = ["css/custom.css"]
    customJS = ["js/custom.js"]

[[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/bigbes/bigbes"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "All posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4
